// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/andremelinski/pos-goexpert/18-DI/product"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

// Passa todo mundo do usecase que precisa dentro do build e ele vai gerir a ordem de injecao de dependencia
// annotation: uma especie de "tags" que ao rodar o projeto, wire verifica se existe e exedcuta o comando.
func NewUseCase(db *sql.DB) *product.ProductUseCase {
	productRepository := product.NewProductRepository(db)
	productUseCase := product.NewProductUseCase(productRepository)
	return productUseCase
}
