version: '3.7'

services:
    # goapp:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - '8080:8080'
    #     volumes:
    #         - .:/app
    goappprod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '8080:8080'
