version: '3.8'

services:
    api:
        container_name: rate-limiter_api
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        networks:
            - default
        depends_on:
            - redis
    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        networks:
            - default
volumes:
    redis-data:

networks:
    default:
