version: '3.8'

services:
    api:
        container_name: rate-limiter_api
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
        environment:
            - DB_HOST=redis
            - DB_PORT=${DB_PORT}
        networks:
            - default
        depends_on:
            - redis

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        env_file:
            - ./.env
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - redis-data:/data
        networks:
            - default

volumes:
    redis-data:

networks:
    default:
